import type { Challenge, RubricRow, SkillMode } from "./types";

const common = (focus: SkillMode): RubricRow[] => [
  {
    criterion: "Reasoning trail",
    emerging: "Names an answer or choice.",
    growing: "Shows some steps or evidence.",
    strong: "Connects evidence to each important choice.",
    transferable: "Tests the reasoning and names when it may fail.",
  },
  {
    criterion: `${focus} craft`,
    emerging: `Attempts the ${focus.toLowerCase()} task.`,
    growing: "Uses one fitting method with support.",
    strong: "Chooses and applies a fitting method independently.",
    transferable: "Adapts the method after feedback or a changed condition.",
  },
  {
    criterion: "Judgment",
    emerging: "Accepts the first result.",
    growing: "Notices an obvious limitation.",
    strong: "Names a trade-off and makes a justified choice.",
    transferable: "Compares alternatives and identifies missing evidence.",
  },
  {
    criterion: "Reflection",
    emerging: "Describes what was made.",
    growing: "Names one difficulty or change.",
    strong: "Explains how a revision improved the work.",
    transferable: "Names a specific next experiment and why it matters.",
  },
];

export const challenges: Challenge[] = [
  {
    id: "paper-bridge",
    title: "The one-sheet bridge",
    kicker: "Make structure visible",
    ageMin: 10,
    ageMax: 14,
    minutes: 45,
    modes: ["Build", "Model"],
    task: "Build a bridge that spans 24 cm and holds the most coins. Before testing, draw or calculate where you expect it to bend first. Run three trials, then revise once.",
    materials: ["1 sheet of A4 or Letter paper", "30 cm tape", "Coins or equal small weights", "Two books", "Pencil and ruler"],
    limits: ["No supports between the books", "The bridge must be lifted off intact", "Record every trial, including failures"],
    reflection: ["Which prediction matched what happened?", "What did your revision trade away?", "What would you measure with better tools?"],
    rubric: common("Build"),
  },
  {
    id: "explain-black-box",
    title: "Explain a black box",
    kicker: "Turn examples into a rule",
    ageMin: 10,
    ageMax: 16,
    minutes: 30,
    modes: ["Explain", "Model"],
    task: "Ask a partner to invent a number rule with one input and one output. Use at most eight examples to infer it. Then make two explanations: one for a 9-year-old and one using algebra or pseudocode.",
    materials: ["Paper", "Pencil", "A partner with a secret rule"],
    limits: ["At most eight input questions", "The rule must work on whole numbers from 0 to 20", "Your partner may only answer with outputs"],
    reflection: ["Which question revealed the most?", "Could another rule fit your examples?", "What changed between your two explanations?"],
    rubric: common("Explain"),
  },
  {
    id: "debug-recipe",
    title: "Debug a human algorithm",
    kicker: "Find ambiguity by running it",
    ageMin: 10,
    ageMax: 13,
    minutes: 35,
    modes: ["Debug", "Collaborate"],
    task: "Write exact instructions for drawing a simple geometric creature. Give only the instructions to a partner. Compare their result with your intent, locate three ambiguities, and publish a revised algorithm.",
    materials: ["Two sheets of paper", "Two pencils", "A willing partner"],
    limits: ["No pointing or answering questions during the first run", "Use only shapes, positions, and measurements", "Preserve the first result as evidence"],
    reflection: ["Which word allowed two interpretations?", "Did the person or the instruction fail?", "How did your tester change the algorithm?"],
    rubric: common("Debug"),
  },
  {
    id: "fair-score",
    title: "Design a fair score",
    kicker: "Make values computable",
    ageMin: 12,
    ageMax: 16,
    minutes: 60,
    modes: ["Model", "Critique"],
    task: "Score three fictional projects from 1–10: Shade garden (cost 7, reach 6, speed 4, certainty 8); bus shelter (4, 8, 7, 5); tool library (6, 5, 6, 4). Invent weights, rank them, then change one weight and test the result.",
    materials: ["Paper or spreadsheet", "The project table on the challenge sheet", "Calculator (optional)"],
    limits: ["Use at least three factors", "No single factor may decide the entire score", "Include one factor that is hard to measure"],
    reflection: ["Whose priorities are hidden in the weights?", "Which ranking is least stable?", "What should remain a human decision?"],
    rubric: common("Model"),
  },
  {
    id: "claim-audit",
    title: "Audit a confident claim",
    kicker: "Separate evidence from polish",
    ageMin: 12,
    ageMax: 16,
    minutes: 40,
    modes: ["Critique", "Explain"],
    task: "Choose a confident claim from an advert, article, or AI response. Map what is claimed, what evidence is offered, what is missing, and one check that could change your mind. Rewrite it with honest uncertainty.",
    materials: ["A saved or printed claim", "Paper", "Two independent reference sources"],
    limits: ["Do not share personal information", "Judge the claim, not its author", "Label fact, inference, and opinion"],
    reflection: ["What made the claim feel convincing?", "Which check had the highest information value?", "What uncertainty remains?"],
    rubric: common("Critique"),
  },
  {
    id: "tiny-language",
    title: "Invent a tiny language",
    kicker: "Design rules another person can run",
    ageMin: 13,
    ageMax: 16,
    minutes: 75,
    modes: ["Build", "Explain", "Debug"],
    task: "Invent six written commands that direct a token around a 5×5 grid. Specify grammar, write a ten-command program, and ask someone else to execute it without coaching. Add one useful error message.",
    materials: ["Squared paper", "A small token", "Index cards", "A partner"],
    limits: ["Exactly six commands", "At least one command must repeat an action", "Programs must have a clear stopping point"],
    reflection: ["Where did your language surprise its user?", "Which invalid program deserves the clearest error?", "What did simplicity make harder?"],
    rubric: common("Build"),
  },
  {
    id: "estimate-room",
    title: "Estimate the impossible room",
    kicker: "Bound what you cannot count",
    ageMin: 10,
    ageMax: 15,
    minutes: 35,
    modes: ["Model", "Explain"],
    task: "Estimate how many dried beans, paper clips, or ping-pong balls would fit in a room. Make a low and high estimate before measuring anything, then refine using only three measurements.",
    materials: ["Tape measure", "Paper and pencil", "One sample object", "Calculator (optional)"],
    limits: ["Only three measurements", "Give a range, not one magic number", "Account for empty space between objects"],
    reflection: ["Which assumption dominates your answer?", "Why is your range defensible?", "Where else could this method help?"],
    rubric: common("Model"),
  },
  {
    id: "two-person-protocol",
    title: "The two-person protocol",
    kicker: "Coordinate with limited information",
    ageMin: 11,
    ageMax: 16,
    minutes: 45,
    modes: ["Collaborate", "Debug"],
    task: "Two people must recreate the same 12-tile pattern while seated apart. Design a message protocol before seeing the pattern, use it once, then improve it based on mismatches.",
    materials: ["Two matching sets of 12 paper tiles", "A divider or separate rooms", "Paper for messages"],
    limits: ["At most 80 written characters per message", "No drawings or photos in messages", "Keep every message as evidence"],
    reflection: ["What information did you assume was shared?", "Which message format prevented errors?", "Did both people contribute to the revision?"],
    rubric: common("Collaborate"),
  },
  {
    id: "premium-noisy-sensor",
    title: "Tame a noisy sensor",
    kicker: "Find a signal without hiding variation",
    ageMin: 13,
    ageMax: 16,
    minutes: 70,
    modes: ["Model", "Critique", "Build"],
    task: "Collect 30 readings from any harmless changing quantity, design a smoothing rule, and show one situation where the smoothed result misleads.",
    materials: ["Stopwatch or household measuring tool", "Paper or spreadsheet"],
    limits: ["Keep the raw data", "Define your rule before comparing results", "Mark every excluded reading"],
    reflection: ["What counts as noise here?", "Which real change could your method erase?", "Who should choose the smoothing level?"],
    rubric: common("Model"),
    paid: true,
  },
  {
    id: "premium-rule-change",
    title: "Survive a rule change",
    kicker: "Adapt a design without starting over",
    ageMin: 10,
    ageMax: 15,
    minutes: 55,
    modes: ["Build", "Debug"],
    task: "Design a paper launcher for distance. After two trials, draw a surprise constraint card and adapt the same design rather than replacing it.",
    materials: ["Four sheets of scrap paper", "Tape", "Measuring tape", "Three homemade constraint cards"],
    limits: ["No rigid projectiles", "Keep each version", "Change at most two features per trial"],
    reflection: ["Which part was most adaptable?", "What prior decision became expensive?", "What would you modularize next time?"],
    rubric: common("Build"),
    paid: true,
  },
  {
    id: "premium-data-story",
    title: "Tell two true data stories",
    kicker: "See how framing changes meaning",
    ageMin: 12,
    ageMax: 16,
    minutes: 60,
    modes: ["Critique", "Explain"],
    task: "Use the same small public or household dataset to make two accurate but contrasting explanations. Then write a caption that prevents the most likely misreading.",
    materials: ["A small non-personal dataset", "Graph paper or spreadsheet"],
    limits: ["Both stories must be numerically true", "Use the same underlying observations", "Label axes and exclusions"],
    reflection: ["Which design choice shifted the story?", "What would a skeptical reader ask?", "Where is the line between framing and deception?"],
    rubric: common("Critique"),
    paid: true,
  },
  {
    id: "premium-teach-machine",
    title: "Teach a paper machine",
    kicker: "Expose how examples shape rules",
    ageMin: 11,
    ageMax: 15,
    minutes: 50,
    modes: ["Model", "Collaborate"],
    task: "Give a partner examples that teach a hidden sorting rule. They may only classify new cards from your examples. Find the smallest teaching set that avoids a plausible wrong rule.",
    materials: ["20 index cards", "Markers", "A partner"],
    limits: ["No verbal hints after examples are shown", "Include at least two near-misses", "Your rule must be visible on each card"],
    reflection: ["Which example ruled out the strongest alternative?", "How did the learner generalize?", "What would make the lesson unfair?"],
    rubric: common("Collaborate"),
    paid: true,
  },
  {
    id: "premium-compress-map",
    title: "Compress a treasure map",
    kicker: "Keep meaning while shrinking a message",
    ageMin: 10,
    ageMax: 14,
    minutes: 50,
    modes: ["Explain", "Build"],
    task: "Describe a 10×10 treasure map in 120 characters, then in 60. Ask a partner to reconstruct each version and design a compact legend that preserves the most important detail.",
    materials: ["Two copies of a blank 10×10 grid", "Pencil", "A partner"],
    limits: ["No images in the message", "Spaces and punctuation count", "Keep both reconstructions"],
    reflection: ["What information compressed well?", "What became ambiguous first?", "How did shared conventions help?"],
    rubric: common("Explain"),
    paid: true,
  },
  {
    id: "premium-reverse-calculator",
    title: "Reverse-engineer the odd calculator",
    kicker: "Infer behavior from careful tests",
    ageMin: 11,
    ageMax: 16,
    minutes: 45,
    modes: ["Debug", "Model"],
    task: "A partner secretly changes one ordinary calculator rule—for example, rounding after every step. Design the fewest tests you can to identify what changed, then state the limits of your diagnosis.",
    materials: ["Two calculators or calculator apps", "Paper", "A partner"],
    limits: ["No more than ten tests", "Predict each result before running it", "Change only one behavior"],
    reflection: ["Which test separated two explanations?", "What behavior remains untested?", "How would you communicate confidence?"],
    rubric: common("Debug"),
    paid: true,
  },
  {
    id: "premium-budget-negotiation",
    title: "Negotiate a tiny budget",
    kicker: "Make trade-offs visible to a team",
    ageMin: 12,
    ageMax: 16,
    minutes: 60,
    modes: ["Collaborate", "Critique"],
    task: "Plan a fictional neighborhood science day with 20 tokens. Each person gets a private priority card. Agree on a plan, record two rejected options, then reveal the priorities and critique the process.",
    materials: ["20 counters", "Four homemade priority cards", "Paper", "Two to four people"],
    limits: ["Every proposal must show its token cost", "Everyone must paraphrase another view once", "Keep a decision log"],
    reflection: ["Whose constraint shaped the result?", "What made disagreement useful?", "How could the process include a quiet voice?"],
    rubric: common("Collaborate"),
    paid: true,
  },
  {
    id: "premium-confidence-forecast",
    title: "Forecast with honest confidence",
    kicker: "Attach uncertainty to a prediction",
    ageMin: 13,
    ageMax: 16,
    minutes: 55,
    modes: ["Model", "Critique"],
    task: "Make five next-day predictions about ordinary events and assign each a probability. Define what would count as correct before checking, then review whether your confidence matched the outcomes.",
    materials: ["Paper", "A public weather source or household schedule", "Calculator (optional)"],
    limits: ["No prediction about a person’s private behavior", "Use at least three different probabilities", "Do not rewrite predictions after the fact"],
    reflection: ["Which probability was hardest to choose?", "Did one result prove the method good or bad?", "What would more trials reveal?"],
    rubric: common("Critique"),
    paid: true,
  },
];

export const freeChallenges = challenges.filter((challenge) => !challenge.paid);
